fix: don't execute unnecessary requests for anonymous cart on initial load
reactioncommerce/example-storefront pull request #705
Opened 2020-07-15 22:10 UTC by willopez

Resolves #701 
Impact: **minor**
Type: **bugfix**

## Issue
Unnecessary requests for anonymous cart are executed when they should not.

## Solution
Use `lazyQuery`s to control when cart requests are executed.

## Breaking changes

## Testing
1. TBD

2020-07-16 20:57 UTC, manueldelreal approved these changes
LGTM! are we including this in the pending release branch?

2020-07-18 12:25 UTC, janus-reith requested changes
I think using Lazy Query currently is the best solution.
Although the related errors in the Apollo-client repo were closed with the release of 3.0.1, multiple people still observed the described error.
I also tried upgrading apollo-client to the latest v3.0.2 and as that didnt work, also upgraded the remaining apollo packages that we're using to their latest version, also without any success.

After looking at your changes I checked out the PR locally and can confirm that the error is fixed.
Tried out anonymous carts, account carts and reconciliation, all seem to work fine.

The only minor change I'd like to suggest is the wording for `refetchAccountCart` / `refetchCartAnonymous`.

2020-07-18 12:25 UTC, janus-reith commented on hooks/cart/useCart.js
> +    { data: cartDataAnonymous, called: anonymousCartQueryCalled, refetch: refetchCartAnonymous }
I think It was a good idea to rename `refetchCart` to `refetchAccountCart` to avoid confusion, but I would rename `refetchCartAnonymous` to `refetchAnonymousCart` accordingly.
```suggestion
    { data: cartDataAnonymous, called: anonymousCartQueryCalled, refetch: refetchAnonymousCart }
```

2020-07-18 12:27 UTC, janus-reith commented on hooks/cart/useCart.js
> +    { data: cartDataAnonymous, called: anonymousCartQueryCalled, refetch: refetchCartAnonymous }
As described above
```suggestion
    { data: cartDataAnonymous, called: anonymousCartQueryCalled, refetch: refetchAnonymousCart }
```

2020-07-18 12:28 UTC, janus-reith commented on hooks/cart/useCart.js
>        refetchCartAnonymous();
As described above
```suggestion
      refetchAnonymousCart();
```

2020-07-20 18:09 UTC, willopez commented
@manueldelreal Yes, we will include this PR in the upcoming release.

2020-07-20 18:22 UTC, willopez commented
@janus-reith Thanks for the suggestions and testing your suggestion has been implemented.

2020-07-20 18:23 UTC, merged

2020-08-04 07:56 UTC, janus-reith commented
@willopez Looks like the upcoming v3.1.2 might fix this, so we could remove that workaround again: https://github.com/apollographql/apollo-client/pull/6752